import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/navbar/Navbar'
import ReduxProvider from './provides/reduxProvides'
import ToasifyProvides from './provides/toasifyProvides'
import getCurrentUser from './actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentUser()
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ToasifyProvides />
          <Header user={user}/>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
